
# echo -n "user:passwd" | base64
GET http://localhost:8080/hello
Authorization: Basic dXNlcjpwYXNzd2Q=

###

GET http://localhost:8080/hello
Cookie: {{cookie}}
###

# echo -n "john:doe" | base64
GET http://localhost:8080/hello
Authorization: Basic am9objpkb2U=

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "chris",
  "password": "password"
}

> {% client.global.set("cookie", response.headers.valueOf("Set-Cookie")); %}
###

