
# echo -n "user:passwd" | base64
GET http://localhost:8080/hello
Authorization: Basic dXNlcjpwYXNzd2Q=

###

GET http://localhost:8080/hello

###

# echo -n "john:doe" | base64
GET http://localhost:8080/hello
Authorization: Basic am9objpkb2U=

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "passwd"
}
###

